export type REG_B = "REG_B"
declare REG_B: REG_B
export type REG_C = "REG_C"
declare REG_C: REG_C
export type REG_D = "REG_D"
declare REG_D: REG_D
export type REG_E = "REG_E"
declare REG_E: REG_E
export type REG_H = "REG_H"
declare REG_H: REG_H
export type REG_L = "REG_L"
declare REG_L: REG_L
export type REG_HLA = "REG_HLA"
declare REG_HLA: REG_HLA
export type REG_A = "REG_A"
declare REG_A: REG_A
export type REG_F = "REG_F"
declare REG_F: REG_F
export type REG_PC = "REG_PC"
declare REG_PC: REG_PC
export type REG_SP = "REG_SP"
declare REG_SP: REG_SP
export type REG_STOP = "REG_STOP"
declare REG_STOP: REG_STOP
export type REG_INTERRUPTS = "REG_INTERRUPTS"
declare REG_INTERRUPTS: REG_INTERRUPTS
export type MEMORY_ROM = "MEMORY_ROM"
declare MEMORY_ROM: MEMORY_ROM
export type MEMORY_WRAM = "MEMORY_WRAM"
declare MEMORY_WRAM: MEMORY_WRAM
export type MEMORY_ERAM = "MEMORY_ERAM"
declare MEMORY_ERAM: MEMORY_ERAM

export type REG_IDX =
	  REG_B
	| REG_C
	| REG_D
	| REG_E
	| REG_H
	| REG_L
	| REG_HLA
	| REG_A
	| REG_F
	| REG_PC
	| REG_SP
	| REG_STOP
	| REG_INTERRUPTS
	| MEMORY_ROM
	| MEMORY_WRAM
	| MEMORY_ERAM
